Repository UBCSailbot/boat_simulator, pull requests merged in 2023-10, with the labels that each got.

#35 Implement UnitConverter class
  boat_simulator/common/types.py
  boat_simulator/common/unit_conversions.py
  tests/unit/common/test_unit_conversions.py
Labels: enhancement

#33 Create class for boat state
  boat_simulator/common/constants.py
  boat_simulator/common/utils.py
  boat_simulator/nodes/physics_engine/kinematics_computation.py
  boat_simulator/nodes/physics_engine/kinematics_data.py
  boat_simulator/nodes/physics_engine/kinematics_formulas.py
  boat_simulator/nodes/physics_engine/model.py
  tests/unit/common/test_utils.py
  tests/unit/nodes/physics_engine/test_kinematics_computation.py
Labels: physics-engine

#40 Fix mypy errors
  boat_simulator/common/types.py
  boat_simulator/common/unit_conversions.py
  boat_simulator/common/utils.py
  boat_simulator/nodes/physics_engine/fluids.py
  boat_simulator/nodes/physics_engine/kinematics_computation.py
  boat_simulator/nodes/physics_engine/kinematics_data.py
  boat_simulator/nodes/physics_engine/model.py
  launch/main_launch.py
  tests/unit/nodes/physics_engine/test_kinematics_computation.py
Labels: infrastructure

#41 Add mypy CI
  .github/workflows/tests.yml
  launch/main_launch.py
Labels: infrastructure

#42 Fix docstring type
  launch/main_launch.py
Labels: infrastructure
